spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_service_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: subscription_service
    show-sql: false
  flyway:
    enabled: true
    schemas: subscription_service
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
    baseline-version: 1